-- Tạo database
CREATE DATABASE userdb;
CREATE DATABASE orderdb;


\connect userdb;

CREATE TABLE public.roles (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT roles_name_key UNIQUE (name),
	CONSTRAINT roles_pkey PRIMARY KEY (id)
);

CREATE TABLE public.users (
	id serial4 NOT NULL,
	first_name varchar(255) NULL,
	last_name varchar(255) NULL,
	email varchar(255) NULL,
	date_of_birth date NULL,
	gender varchar(10) NULL,
	address varchar(255) NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	phone varchar(20) NULL,
	role_id int4 NULL,
	password varchar(255) NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE public.users ADD CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE SET NULL;

INSERT INTO public.roles (name) VALUES ('ADMIN'), ('USER');

INSERT INTO public.users (first_name, last_name, email, date_of_birth,gender, address, phone, role_id, password) VALUES 
('Nguyen', 'Van A', 'vana@example.com', '1995-05-15', 'Male', '123 Đường A, Hà Nội', '0912345678', 1, 'password123'),
('Tran', 'Thi B', 'thib@example.com', '1992-08-20', 'Female', '456 Đường B, HCM', '0987654321', 2, 'password456');   

-- Tạo bảng orders trong database orderdb
\connect orderdb;

CREATE TABLE public.orders (
	id serial4 NOT NULL,
	user_id int4 NOT NULL,
	fullname varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	phone varchar(255) NOT NULL,
	address varchar(255) NOT NULL,
	order_date timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	status varchar(50) DEFAULT 'PENDING' NULL,
	total_money numeric(10, 2) NULL,
);

INSERT INTO public.orders (user_id, fullname, email, phone, address, status, total_money) VALUES 
(1, 'Nguyen Van A', 'vana@example.com', '0912345678', '123 Đường A, Hà Nội', 'PENDING', 150000.00),
(2, 'Tran Thi B', 'thib@example.com', '0987654321', '456 Đường B, HCM', 'COMPLETED', 250000.00);